services:
  web:
    build: .
    ports:
      - "3000:3000"

    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - PORT=${PORT}

      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}

      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - db

  nginx:
    image: nginx:1.24.0
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

  proxy:
    image: nginx:1.24.0
    ports:
      - "80:80"
    volumes:
      - ./balanced.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mondongo:/data/db

volumes:
  mondongo: